### ISSUE TITLE
dde-preload is a CPU hog

### ISSUE THREAD

**Issue by felixonmars** [fasheng/arch-deepin#129] opened 2015-11-26 03:46 UTC
dde-preload takes 100% CPU (one core) once or twice every minute, and lasts for 10~20s. This costs much battery.

**Comment by gujralam** [comment] 2015-11-30 06:12
When can we expect this issue to be fixed

**Comment by fasheng** [comment] 2015-11-30 06:32
it's ok in upstream, so still need debugging more for arch



2015年11月30日 下午2:12, 下午2:12，在 gujralam <notifications@github.com> 已写:

**Comment by felixonmars** [comment] 2015-11-30 06:38
The CPU usage is acceptable on my PC, too. The described usage in OP was on my laptop (ThinkPad x200s with 8GB ram), which has a low voltage CPU (L9400).

**Comment by felixonmars** [comment] 2015-12-13 05:52
This is after ~20h, look at the CPU time:
![2015-12-13-134731-315607](https://cloud.githubusercontent.com/assets/1006477/11765747/9b2f6916-a1a0-11e5-934e-cfa4e5ea3447.png)

**Comment by felixonmars** [comment] 2015-12-13 16:39
So I believe it is leaking memory too:
![2015-12-14-003835-6ff164](https://cloud.githubusercontent.com/assets/1006477/11768025/18345c96-a1fb-11e5-9382-af293bf6cf7e.png)

**Comment by fasheng** [comment] 2015-12-14 05:39
Hmm, the upstream fixed one similar issue caused by xgb/xbgutils which is out of date. But for arch, we always use the latest code..

**Closed** 2016-03-05 08:53 UTC
Labels: daemon
