### ISSUE TITLE
download library error

### ISSUE THREAD

**Issue by fneig** [fasheng/arch-deepin#71] opened 2015-05-31 06:33 UTC
When I use pacman -Syy deepin, the following error occurred

    error: failed retrieving file 'home_metakcahura_arch-deepin_Arch_Extra.db' from anorien.csc.warwick.ac.uk : Resolving timed out after 10521 milliseconds
    error: failed to update home_metakcahura_arch-deepin_Arch_Extra (download library error)
    error: target not found: deepin

The same results using http://download.opensuse.org/repositories/home:/metakcahura:/arch-deepin/Arch_Extra/$arch

Thanks you!

**Comment by fasheng** [comment] 2015-05-31 09:47
I just installed deepin to a fresh archlinux two days ago, and everythin is fine.

Maybe caused by your network, so could you access the repo directly in browser?

http://download.opensuse.org/repositories/home:/metakcahura:/arch-deepin/Arch_Extra/

**Comment by fneig** [comment] 2015-05-31 10:10
Yes, I can access.

**Comment by fasheng** [comment] 2015-06-01 01:03
Well, looks strange. Please paste you `/etc/pacman.conf` here.

**Comment by fneig** [comment] 2015-06-01 01:21
I have successfully installed deepin desktop, today successfully installed. Yesterday, the network may be bad.

**Comment by fasheng** [comment] 2015-06-01 03:07
OK, I close this issue now. Have a fun!

**Closed by fasheng** 2015-06-01 03:07 UTC
